name: test

# on 配置项用于配置该仓库的什么分支触发什么事件后进行该 ci 的调用
on:
  push:
    branches: master, test_github_ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: curl http://39.104.62.0:8181/cgi/health_check -v
